### ISSUE TITLE
Open Source Compliance 

### ISSUE THREAD

**Issue by merrcury** [Diversity-In-DSC/DSC-WoW-Front-end#43]
Hi, 

Would you guys mind making the DSC WOW frontend website Open Source to be used by other hackathons?

**Comment by aravindvnair99** [comment]
> Hi,
> 
> Would you guys mind making the DSC WOW frontend website Open Source to be used by other hackathons?

Hey @merrcury!

The source code is already available in this repository. You can check the code out. Additionally, you can check these as well:
- https://github.com/Diversity-In-DSC/DSC-WoW-Old-Front-end
- https://github.com/Diversity-In-DSC/code-off-duty

**Comment by aravindvnair99** [comment]
> Hi,
> 
> Would you guys mind making the DSC WOW frontend website Open Source to be used by other hackathons?

Hey @merrcury!

The source code is already available in this repository. You can check the code out. Additionally, you can check these as well:
- https://github.com/Diversity-In-DSC/DSC-WoW-Old-Front-end
- https://github.com/Diversity-In-DSC/code-off-duty

If there's something, specific you are looking for, let me know and I will try to help. Else I will close this issue and the code is already available in the 3 repositories.

**Comment by merrcury** [comment]
Hi @aravindvnair99 

Source Code is available but due to the unavailability of LICENSE, It's not Open Source Compliant. So, If You could add a LICENSE (preferably MIT with attribution) that would help us and other people Or If You don't wish to make it an Open Source Complaint, We can make an "Agreement to Use" to let us use the source code.

**Comment by merrcury** [comment]
All three repositories are missing LICENSE. So, LICENSE is required in all repositories.

**Comment by aravindvnair99** [comment]
> Hi @aravindvnair99
> 
> Source Code is available but due to the unavailability of LICENSE, It's not Open Source Compliant. So, If You could add a LICENSE (preferably MIT with attribution) that would help us and other people Or If You don't wish to make it an Open Source Complaint, We can make an "Agreement to Use" to let us use the source code.



> All three repositories are missing LICENSE. So, LICENSE is required in all repositories.

Hey @merrcury!

I understand, let me check with the team and get back to you.

**Comment by aravindvnair99** [comment]
Hey @merrcury!

I have updated all 3 repositories. Please recheck and thanks for reaching out! :)
